#!/usr/bin/env bash
EMSDK_TESTED_VERSION="2.0.27"
EMSDK_REPO_URL="https://github.com/emscripten-core/emsdk.git"

cd `git rev-parse --show-toplevel`
mkdir -p tmp
DIR=`pwd`
if [ ! -d "tools/emsdk" ]; then
	cd "tools/"
	git clone "$EMSDK_REPO_URL" emsdk
else
	cd "tools/"
fi
cd emsdk/
git pull
./emsdk install "$EMSDK_TESTED_VERSION"
./emsdk activate "$EMSDK_TESTED_VERSION"

source "emsdk_env.sh"
cd ../../
rm -f web/index.html web/index.js web/index.wasm
make -j nujel
./nujel tools/buildwasm-filesystem.nuj
make -j release.wasm
