#!/usr/bin/env bash
cd "$(dirname "$0")"
cd ../

make clean 2> /dev/null > /dev/null
CFILES=`find bin lib tools -type f -name '*.c'`
HFILES=`find bin lib tools -type f -name '*.h'`
NUJFILES=`find binlib stdlib tools -type f -name '*.nuj'`

CLINES=`wc -l $CFILES | tail -n1 | awk '{print $1}'`
HLINES=`wc -l $HFILES | tail -n1 | awk '{print $1}'`
NUJLINES=`wc -l $NUJFILES | tail -n1  | awk '{print $1}'`
printf 'C Source: %7s\n' "$CLINES"
printf 'C Header: %7s\n' "$HLINES"
printf 'Nujel:    %7s\n' "$NUJLINES"
