name: CI

on:
  push:
    branches: [ master, develop ]

jobs:
  build-windows:
    name: ${{matrix.os}}-${{ matrix.sys }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        sys: [mingw64, mingw32, ucrt64, clang64]
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        install: base-devel
        pacboy: toolchain:p
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j
    - name: Run Tests
      run: make test
  release-windows:
    name: release-windows-${{ matrix.sys }}
    needs: build-windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        sys: [mingw64, ucrt64, clang64]
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        install: base-devel
        pacboy: toolchain:p
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j
    - name: Run Tests
      run: make test.slow
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: Nujel-windows-${{ matrix.sys }}-${{ github.ref_name }}
        path: "./nujel.exe"
        retention-days: 7
  build-macos:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j
    - name: Run Tests
      run: make test
  release-macos:
    needs: build-macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: make -j release
    - name: Run Tests
      run: make test.slow
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: Nujel-macos-${{ github.ref_name }}
        path: "./nujel"
        retention-days: 7
  build-linux:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j release
    - name: Run Tests
      run: make test
  release-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install -y musl-dev musl-tools
    - name: Build Release
      run: make -j release.musl
    - name: Run Tests
      run: make test.slow
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: Nujel-linux-${{ github.ref_name }}
        path: "./nujel"
        retention-days: 7
  release-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j
    - name: Compile WASM REPL
      run: bash tools/buildwasm
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: Nujel-Web-${{ github.ref_name }}
        path: "./web/"
        retention-days: 7
  deploy:
    runs-on: ubuntu-latest
    needs: [release-wasm, release-macos, release-windows, release-linux]
    steps:
    - uses: actions/download-artifact@v2
    - name: Create archive
      run: tar -czf nujel-${{ github.ref_name}}-${{ github.sha }}.tar.gz ./*
    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: Nujel-${{ github.ref_name }}-${{ github.sha }}
        path: "./nujel-${{ github.ref_name}}-${{ github.sha }}.tar.gz"
        retention-days: 7