name: WASM CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j
    - name: Compile WASM REPL
      run: bash tools/buildwasm
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST_KEY }}
    - name: Upload to wolkenwelten.net
      run: |
        rsync -avze 'ssh -p 42' --delete ./web/ github@wolkenwelten.net:/home/github/nujel/${GITHUB_REF##*/}/
